qwt5.lwr
=> qwt5: fixed escaped prefix for configure

gsl.lwr
=> fixed terrible typo

doxygen.lwr, liblog4cpp.lwr, qwt5.lwr, wxpython.lwr
Now, all dependencies for gnuradio-default are met.
=> Add missing pacman packages

pyqwt5.lwr
=> pyqwt5: updated source URL

cheetah.lwr, lxml.lwr, pycairo.lwr
Added pip install commands to `cheetah.lwr`, `lxml.lwr` and `pycairo.lwr`.
=> Add pip installs 

airspy.lwr, bladeRF.lwr, flex.lwr, gfortran.lwr, glfw3.lwr, gqrx.lwr, gr-fcdproplus.lwr, gr-iqbal.lwr, gr-osmosdr.lwr, gtest.lwr, hackrf.lwr, lapack.lwr, libbzip.lwr, libmp3lame.lwr, libpcap.lwr, libshout.lwr, libsndfile.lwr, libtalloc-dev.lwr, libxml.lwr, libxslt.lwr, python-zmq.lwr
fixes issue dicussed on mailing-list
=> Add pacman to python-zmq

gr-pico.lwr
Adding the DRS Picoflexor OOT Module into gr-recipes
=> Added gr-pico recipe for PyBOMBS build of gr-pico OOT module

qwt6.lwr, qwtplot3d.lwr
Add new recipes for gr-inspector dependencies and update gr-inspector itself
=> Dependencies for gr-inspector

limesuite.lwr, soapyrtlsdr.lwr, soapysdr.lwr, sqlite.lwr
=> added support for LimeSDR

gr-iridium
=> Add recipe for gr-iridium

python-tk.lwr
This fixes #100 by adding tkinter to the rpm list
=> python-tk: added tkinter for F25

osmo-tetra.lwr
=> fixed missing dependency "libosmocore"

gr-limesdr.lwr
This recipe doesn't yet work, but it will as soon as https://github.com/myriadrf/gr-limesdr/pull/8 is merged.
/cc @ztamosevicius
=> Add recipe for gr-limesdr.

gr-bokehgui.lwr
repo-path seems to be changed...
=> fixed bad repo-path

soapysdr.lwr
=> Disable python3 when compiling soapysdr

gr-fosphor.lwr, gr-iqbal.lwr, gr-op25.lwr, gr-osmosdr.lwr, libosmo-dsp.lwr, libosmocore.lwr, osmo-fl2k.lwr, osmo-sdr.lwr, osmo-tetra.lwr, rtl-sdr.lwr
I'm gonna leave this here for discussion, but I've been on a few filtered networks lately that block the git native protocol
=> switch osmocom sources to github to improve checkouts on filtered networks

gnuradio.lwr, gnuradio38.lwr, gtk3.lwr, pygobject.lwr, pyqt5.lwr, pyyaml.lwr
Continuation of PR #155.
I've tested it in a clean Fedora 30 and Ubuntu 18.04 docker containers, using python3 and pip3.
=> Add some more gnuradio 3.8 dependencies

alsa.lwr
=> updating alsa.lwr (fix #198)

libiio.lwr
Signed-off-by: Jeff Long <willcode4@gmail.com>
=> libiio: use latest tag

libhidapi.lwr
Signed-off-by: Jeff Long <willcode4@gmail.com>
=> libhidapi: add rpm source libhidapi-dev

gnuradio39.lwr
simple copy paste of gnuradio-master but referencing maint-3.9 per @willcode via discuss-gnuradio
=> adding explicit recipe for maint-3.9

hackrf.lwr
The project was recently moved from @mossmann's personal GitHub account to the @greatscottgadgets organization.
=> Update URL of HackRF repo

uhd.lwr
This change was suggested by @willcode.
=> uhd: Use UHD-4.2 branch
