gnuradio.lwr

If the default behavior is going to be a binary package install, then environments that set a source build of gnuradio probably want the full repo.

perform a full-depth clone of gnuradio

---

boost.lwr

Building boost from source requires running bootstrap and bjam from the source tree. There may be a better way to do this, but I found this to work. The build still takes place in build.
Related, is there a recipe variable that contains the full path to the build directory?

run boost commands from boost source-tree

---

pyqwt5.lwr

Compilation currently fails due to unresolved 'reprefix' variable. The
following incorrect sed command is executed during install with prefix
'/usr/local':
sed 's/\/usr\/share\/sip\//\/share\/sip\//' qwt5qt4/Makefile > qwt5qt4/Makefile.tmp
This command results in an incorrect Makefile and failed compilation.
This fix replaces 'reprefix' with 'prefix' so the following sed command
is executed:
sed 's/\/usr\/share\/sip\///usr/local\/share\/sip\//' qwt5qt4/Makefile > qwt5qt4/Makefile.tmp

Fix pyqwt5 compilation

---

qt4.lwr

The former URL is no longer reachable. I replaced it with a valid one.

Corrupt URL in qt4 recipe

---

mako.lwr

In packagers/pip.py, the pip packager does not have the ability (AFAIK) to get a version number... it returns only True or False depending on whether there's a version at all... I guess this is the right thing since the pip package should be up to date.
This was causing a TypeError in utils/vcompare.py.

pybombs pip definition doesn't check versions :(

---

gr-mapper.lwr

gr-burst (which is in gr-recipes) depends on gr-mapper

adding gr-mapper back into recipes

---

bison.lwr

Investigating #18 I noticed that apache-thrift needs bison 2.5 or higher:
```bash
$ ./configure
[...]
checking for bison... yes
checking for bison version >= 2.5... no
```

Fixed bison version requirement

---

networkx.lwr
pygraphviz.lwr

gr-perf-monitorx calls networkx and pygraphviz. pygraphviz should be a package-level
dependency for networkx, but for some reason isn't.
Tested with a maint build for gnuradio and uhd.

Recipes added for networkx and pygraphviz, dependency on networkx for gnuradio

---

libtool.lwr

For things to work without building this standard tool from source on
many rather modern RH/Fedora/CentOS distro's, we need to use 2.4.2
(which is the packaged version on CentOS 7, FC 22).
I haven't been able to find a package that actually requires >=2.4.6.
Since I've never built libtool locally to get any GR running, I'm positive this isn't necessary on Fedora.
On CentOS 7, I verified it's not necessary to build libtool from source for any of the dependent packages during a "gnuradio" installation.

Downgrading libtool version requirement

---

mcpp.lwr
mpc.lwr
mpfr.lwr
networkx.lwr
osmo-sdr.lwr
protobuf.lwr
pulseaudio.lwr
pygraphviz.lwr
python-matplotlib.lwr
rtl-sdr.lwr
wireshark.lwr

As mentioned in previous PR I added pacman sources to some more recipes.
I used a diff of recipes containing deb: lines but no pacman lines. Maybe this reduces compile time for Arch users :)

add pacman sources to missing recipes

---

python-zmq.lwr

Fedora 24 renamed "python-zmq" to "python2-zmq".  This change will try the old name first, then "python2-zmq".

Update name of python-zmq for rpm distributions

---

qwt6.lwr

Some users had problems installing qwt6.1 since it's not in the 14.04 repos. I added the build from source properties to the recipe.

Update qwt6 recipe

---

gr-iio.lwr
libiio.lwr

Libiio v0.7 brings USB support, and is overall more stable.
The gr-iio recipe was pointing to the wrong git repository. This was fixed in recipes-legacy, but apparently didn't make it here. The version 0.2 brings a couple more blocks including the 'iio_math' and 'iio_math_gen' blocks.

Update libiio and gr-iio

---

gnss-sdr.lwr
six.lwr

This PR includes a new recipe for python-six, which is now also required by the master branch of VOLK

Add new gnss-sdr dependencies python-mako and python-six

---

gr-drm.lwr

Probably because of repo restructuring in
https://github.com/kit-cel/gr-drm/commit/5c2dfaa4a96f5e8c7bd4f468fc8ef79a3d9e2d0e
Fixes build.

the 'gr-drm/' prefix is no longer necessary

---

x11.lwr

This commit is to fix issue #77 on Debian based systems.

x11: Fix deb package case error.

---

pyqt5.lwr

A recent change in one GUI tool from Ettus Research (uhd_image_builder_gui.py) requires PyQt5, so I'm adding this to have it as a dependency for the RFNOC recipe in the Ettus' recipes repository

Adding pyqt5 recipe

---

pyqt5.lwr

Briefly:
- The versioning scheme the recipe has for rpm was not being picked up correctly, so the build system was going directly for source install
- The version for the source tarball that the recipe had required a new sip version, which is not installed as a requirement. Rolling back a couple of versions to another stable tarball seems to do the trick (as per the sip installation from the recipe that pybombs also provides)
I had to do something extra for the source installation, I describe as follows in case someone can give me a lead. I'm not sure if this step can be added to the recipe:
The source installation also required qmake (which comes with qt5). I had to explicitly add that to the path:
$ cd /
$ find -iname qmake
and add the location where it was found:
$ export …

pyqt5: fix fedora build and source version

---

alsa.lwr
boost.lwr
cheetah.lwr
ffi.lwr
fftw.lwr
libbzip.lwr
libjpeg.lwr
libpng.lwr
lxml.lwr
numpy.lwr
pixman.lwr
pkg-config.lwr
pycairo.lwr
pygobject.lwr
pygtk.lwr
pyqt4.lwr
pyqwt5.lwr
python-tk.lwr
python-zmq.lwr
python.lwr
qt4.lwr
qt5.lwr
scipy.lwr
setuptools.lwr
sip.lwr
ssl.lwr
twisted.lwr
wxpython.lwr
zeromq.lwr

The openSUSE linux distribution uses rpm packages but a different naming convention than does Redhat.  This pull request adds openSUSE specific packages to the rpm satisfy field.
(Apologies for combining two ostensibly independent submissions, they were developed jointly.)
Python virtual environments (venvs) allow users to create somewhat isolated installations of python on a single machine.  These venvs allow a user to have a variety of python module support and versioning appropriate to their specific project or application.  It also allows the developer to experiment with modules without the risk of causing a conflict within his base OS, which may use particular python utilities or library versions.  This can be especially important when creating minimal environments for deployment. …

openSUSE and virtualenv recipes

---

networkx.lwr
pygraphviz.lwr
python-matplotlib.lwr
python-tk.lwr
python.lwr
scipy.lwr
setuptools.lwr
six.lwr

On Fedora 26 the gnuradio build fails because several python packages are available only with python2 prefix

On Fedora 26 install python2-* packages

---

gr-iio.lwr

Tag v0.3 includes Pluto specific blocks and block API updates.
Signed-off-by: Travis Collins <travis.collins@analog.com>

Update gr-iio recipe to tag v0.3

---

sqlite.lwr

this fixes pybombs usage on fedora based systems. To find the sqlite package

add rpm to sqlite

---

libosmocore.lwr

It depends on gnutls since commit ed029dfab and ./configure fails when
not found and not disabled explicitly
https://github.com/osmocom/libosmocore/blob/ed029dfab/configure.ac#L133-L145

libosmocore depends on gnutls

---

osmo-fl2k.lwr

This PR adds a recipe for [osmo-fl2k](https://osmocom.org/projects/osmo-fl2k/wiki). Since it can be used with GNU Radio, I thought it would be useful to have it in PyBOMBS.

Add recipe for osmo-fl2k.

---

airspyhf.lwr
soapyairspy.lwr
soapyairspyhf.lwr
soapybladerf.lwr
soapymultisdr.lwr
soapyremote.lwr
soapyuhd.lwr

This adds Soapy SDR modules for the following hardware:
* Airspy
* Airspy HF+
* BladeRF
* USRP (via UHD)
It also adds SoapyMultiSDR (for multi-device support) and SoapyRemote (for remote operation).
The Airspy HF+ driver was not present in gr-recipes, so I added it. I also updated the Airspy recipe to point to the new location as the GitHub repository has been renamed.
@mbr0wn

Add more SoapySDR modules.

---

matio.lwr

Add matio, a library for Octave/Matlab .mat file I/O

---

gr-burst.lwr
pybitarray.lwr

First time working with pybombs and gr-recipes, so let me know if there is more work/testing I need to do. `pybombs install gr-psk-burst gr-burst` works at install, but the various blocks fail at runtime with a missing bitarray module. This change should fix that.

add dependency on pybitarray to gr-burst, gr-psk-burst

---

apache-thrift.lwr

See https://github.com/gnuradio/pybombs/issues/465
On recent Debian systems, Apache Thrift 0.9.3 does not compile, therefore bumping version to 0.10.0. (Most recent version 0.11.0 breaks gnuradio build).

Fixing compilation issue on more recent systems

---

libtalloc-dev.lwr
pcsclite.lwr

The alioth.debian.org service has been discontinued and replaced by salsa.debian.org

 Update talloc and pcsclite source URLs 

---

gmp.lwr

Without it installation in a centos 7 container fails with 
```
$ pybombs prefix init -a default -R gnuradio-default ~/gnuradio/default
-- checking for module 'gmp'
--   package 'gmp' not found
-- Could NOT find GMP (missing:  GMPXX_LIBRARY GMP_INCLUDE_DIR) 
-- checking for module 'mpir >= 3.0'
--   package 'mpir >= 3.0' not found
-- Could NOT find MPIR (missing:  MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
Could NOT find MPLIB (missing: MPLIBXX_LIBRARY MPLIB_LIBRARY
MPLIB_INCLUDE_DIR)
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
cmake/Modules/FindMPLIB.cmake:26 (find_package_handle_standard_args) …
```

Add gmp-devel rpm package

---

libudev.lwr

On recent Fedora and Centos versions the libudev is provided by
systemd-devel package

libudev: Install systemd-devel

---

pygraphviz.lwr

PyBOMBS.recipes - WARNING - Recipe for `pygraphviz' is invalid.

pygraphviz: Remove the duplicated rpm entry

---

gnuradio.lwr

In light of the fact that the recipe doesn't contain next dependencies, and 3.7.XX has reached a level of usefulness that makes it feasible for most people that use pybombs, we should be migrating away from master to save us from major headache.
We should also be having a GNU Radio development version recipe.

Make the GNU Radio recipe build maint-3.7 instead of master

---

swig.lwr

source download of 3.0.12, since that is what is running on most
supported distros.

Updated SWIG to use at least 2.8

---

gr-ldpc.lwr

```
PyBOMBS.get_recipe - ERROR - Error fetching recipe `g':
Package g has no recipe file!
```

fix build error.

---

libiio.lwr

0.7 is just way too old, the plutosdr soapysdr driver requires a 3
year old api call found in 0.9.

crank minimum required libiio version for plutosdr

---

liblog4cpp.lwr

If log4cpp was build from source, version 1.1.1 contained illegal instructions in C++17, which affect all other softwares linking to it. Upstream version 1.1.3 solves this issue.

liblog4cpp: update source package version, allowing C++17 usage

---

gr-foo.lwr
gr-ieee-80211.lwr
gr-rds.lwr

I ported my modules and switched over to the proposed dev scheme for 3.8, i.e., the legacy branch was renamed to *maint-3.7*.

update branches of foo, 802.11, rds

---

libpolarssl.lwr

> PolarSSL is now part of ARM Official announcement and rebranded as Mbed TLS.
polarssl.org is redirected to tls.mbed.org now.  
This may cause some certification validation error of wget.
update the tarball link fix the problem.

Fix libpolarssl tarball location

---

gnuradio38.lwr
python-click-plugins.lwr
python-pyqtgraph.lwr
qwt6.lwr

- Change gnuradio38 branch to maint-3.8
- Add dependency python-click-plugins, fixes #153
- Add dependency python-pyqtgraph, fixes #154
I could successfully install GNU Radio 3.8 with these recipes, however I might have missed dependencies that were already installed on my system.

Update recipes to GNU Radio 3.8 release

---

qwt6.lwr

In Debian testing the libqwt-dev package has been removed so replace &&
with ||. Fix the rpms as well.
Update the source URL to version 6.1.4 to fix the following errors:
qwt_transform.h:110:5: error: ‘QT_STATIC_CONST’ does not name a type
110 | QT_STATIC_CONST double LogMin;
| ^~~~~~~~~~~~~~~
qwt_transform.h:111:5: error: ‘QT_STATIC_CONST’ does not name a type
111 | QT_STATIC_CONST double LogMax;
| ^~~~~~~~~~~~~~~
Fixes #161

qwt6: Install either libqwt-qt5-dev or libqwt-dev

---

gr-foo.lwr
gr-ieee-80211.lwr
gr-iio.lwr

I was just moving from gr 3.7 to 3.8 and ran into some error messages as some recipes default to git branches for 3.7, but the gnuradio recipe defaults to 3.8

gr-foo, gr-iio defaulting to maint-3.8 branches

---

libosmocore.lwr

In [libosmocore 1.3.0 (ea2afb21d)](https://github.com/osmocom/libosmocore/blob/1.3.0/configure.ac#L176-L190) the SCTP support was added and enabled
by default. The build fails when sctp library is not found.
Support for SCTP on non Linux operating systems is problematic and SCTP
is not needed by most SDR applications so buid without it by adding
--disable-libsctp to configure options.

libosmocore: Build without SCTP support

---

libvolk.lwr

In order to remove VOLK as a GR submodule, a PyBOMBS recipe to build it and make GR depend on it, is required. This PR is supposed to support that goal.

volk: Add libvolk recipe

---

gnuradio-master.lwr

Currently there are two recipes for use with the `pybombs prefix` command: 
* `gnuradio-stable` builds maint-3.7
* `gnuradio-default` builds maint-3.8
It would be convenient to have one to build master, so I've added that here. The `gnuradio-master` recipe is a copy of `gnuradio-default` with the following addition:
```
gnuradio:
gitbranch: master
```

Add a prefix recipe for GNU Radio master

---

gnuradio.lwr
gnuradio38.lwr

GNU Radio 3.8 fails to install on Ubuntu 20.04 because the recipes specify a dependency on PyGTK. The PyGTK dependency was replaced with PyGObject in GNU Radio 3.8 (https://github.com/gnuradio/gnuradio/commit/395bd4415cc92217886d0f2a4f026a6070e1748b) so pygtk should be removed from the GNU Radio 3.8 recipes.

gnuradio: Remove dependency on PyGTK

---

gqrx.lwr

Gqrx fails to build on Ubuntu 20.04 because the recipe lists a dependency on Qt4. Gqrx in fact depends on Qt5, which already appears in the dependency list. Therefore qt4 can simply be removed.

gqrx: Remove dependency on qt4

---

pygtk.lwr

This commit changes the packages that are installed for python3.
Otherwise a system without Python2 will start to compile e.g. pango from source.
Still, the installed package would be incorrect.
Fix #182 
I hope this is the correct package to install. Or should this just be an empty dependency in case of Python3? It seems like this dependency is unnecessary.

package: install correct packages

---

gnuradio.lwr

dep: Add libvolk dependency to gnuradio

---

gr-osmosdr.lwr

The gr-osmosdr recipe is missing some of the optional dependencies needed to build modules for its supported SDR boards. As a result, support for Airspy HF and FUNcube Dongle hardware is not built. This change adds the missing dependencies.
In addition, SDRplay support is not built, even if the required library is present, because gr-osmosdr requires the ENABLE_NONFREE config option to be set. I've added it to config_opt.

gr-osmosdr: add missing dependencies

---

gr-satellites.lwr

gr-satellites does not require libfec since v3.3.0 and it
requires python-construct since a while ago.
I have also taken the occasion to update the description.

Update gr-satellites recipe dependencies

---

gnuradio-default.lwr

Some projects are now targeting GNU Radio 3.9 on their master branches, so it's necessary to check out maint-3.8 (or similar) to build with GNU Radio 3.8. Here I've updated the gnuradio-default (3.8) recipe to override the git branch for some recipes that need this.

Use maint-3.8 branches when building with GNU Radio 3.8

---

curl.lwr
gcc.lwr
gr-mapper.lwr
libfec.lwr
libjpeg.lwr
libtiff.lwr
libudev.lwr
mbelib.lwr
pygraphviz.lwr
sqlite.lwr
subversion.lwr
x11.lwr

I ran `pybombs lint` against everything in gr-recipes, and it complained loudly about some broken `depends`:
```
[VERY BAD] Dependencies is not a list: None
```
It looks like recipes that don't have any dependencies should not have a `depends` property, so I've removed them here.

Fix malformed depends

---

libvolk.lwr

VOLK master relies on cpu_features now. The recipe asks to clone VOLK
master. Thus, we need to clone VOLK recursively now. This shouldn't
break things for older version because it the `--recursive` flags would
just fall through.

volk: Update VOLK recipe with git recursive

---

libvolk.lwr

Fixes https://github.com/gnuradio/gr-recipes/issues/252.
VOLK has renamed its master branch to main (https://github.com/gnuradio/volk/issues/461) so its recipe needs to be updated accordingly.
/cc @jdemel

volk: Update branch name

---

soapysdrplay.lwr

Depends on manual installation of SDRPlay_RSP_API-Linux-3.X
software from sdrplay.com.
Signed-off-by: Jeff Long <willcode4@gmail.com>

soapysdrplay: add recipe

---

gnuradio-default.lwr
libmnl.lwr
libosmocore.lwr
opencl.lwr

This fixes gr-iqbal, gr-osmosdr, gr-fosphor, and gr-gsm on GNURadio 3.8 by pinning them to the appropriate git branch for 3.8, and by adding some missing dependencies. This fixes https://github.com/gnuradio/gr-recipes/issues/246.

Fix Osmocom packages on GNURadio 3.8

---

pyconstruct.lwr

Fedora calls this package `python3-construct`. Since pyconstruct doesn't uninstall/update nicely from its tar source, it helps to be able to use the system one.

pyconstruct: add python3-construct to satisfy

---

qt5.lwr

Debian stable as of bullseye no longer has a qt5-default package, as
qt4 support was removed and qt5 is default.  Distros based on debian
will not have this package.
Relates to https://github.com/gnuradio/pybombs/issues/555
On Debian 11 (bullseye), I ran the installation with the updated qt5 recipe and everything installed fine, and I was able to run gnuradio-companion.  I'm not sure if there are other tests to run to confirm, apologies, quite new to gnuradio.  
Note answer here for Ubuntu:
https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1926802
Honestly, I'm not clear if this fix is really correct, because i think the recipe needs to be sync'd to the Debian 11 epoch.  Pre Debian 11, the old recipe works, where-as post Debian 11, the old recipe wont.

qt5: debian distros based on bullseye no longer require qt5-default

---

gqrx.lwr

The project was recently moved from the author's personal GitHub account to a separate GitHub organization.

Update URL of Gqrx repo

---

lxml.lwr
mako.lwr
pygobject.lwr
python-click-plugins.lwr
python-pyqtgraph.lwr
python-zmq.lwr

Hi, 
I was trying to install Gnuradio 3.8 on my Arch Linux setup and I encountered these 2 issues I gave below.
```
[INFO] Prefix Python version is: 3.9.7
[INFO] Prefix Python version is: 3.9.7
[INFO] Installing default packages for prefix...
[INFO] 
- gnuradio
[INFO] Phase 1: Creating install tree and installing binary packages:
[ERROR] Package has no install method: python-click-plugins
and 
[INFO] Prefix Python version is: 3.9.7
[INFO] Prefix Python version is: 3.9.7
[INFO] Installing default packages for prefix...
[INFO] 
- gnuradio
[INFO] Phase 1: Creating install tree and installing binary packages:
[ERROR] Package has no install method: python-pyqtgraph
```
I have fixed the issue by changing responsible .lwr files for those packages.

Pyqtgraph and click plugins .lwr file correction for arch linux

---

gr-fosphor.lwr
gr-iqbal.lwr
gr-op25.lwr
gr-osmosdr.lwr
libosmo-dsp.lwr
libosmocore.lwr
osmo-fl2k.lwr
osmo-sdr.lwr
osmo-tetra.lwr
rtl-sdr.lwr

Osmocom recently migrated to Gitea, so their repositories have new URLs. HTTP forwarding is working for now, but we may as well update recipes to use the new addresses.

Update osmocom.org git URLs

---

gnuradio-main.lwr

Remove gnuradio-master as a separate step.
Signed-off-by: Jeff Long <willcode4@gmail.com>

gnuradio-main: default GNU Radio branch is now "main"

---

gnuradio.lwr

The gr-soapy module was added to GNU Radio in version 3.9.2. Making it a dependency will ensure that gr-soapy gets built when GNU Radio is installed.

gnuradio: Add soapysdr as a dependency

---

gnuradio.lwr

GNU Radio 3.10 added gr-iio, but this module doesn't build unless libiio is present. Adding it as a dependency will ensure that it's always installed prior to building GNU Radio.

Add libiio dependency to gnuradio recipe

---

libiio.lwr

This change was made for the processing "gnuradio-default" recipe of the gnuradio/pybombs repository.
Since the default branch in the "analogdevicesinc/libiio" repository became "main" instead of "master" we got error while building:
> Cloning into 'libiio'...
> fatal: Remote branch master not found in upstream origin

Support for renamed branch "main" in the repository "analogdevicesinc/libiio"

---

gnss-sdr.lwr

The old `http` seems to be causing problems in some environments.

Change http to https in gnss-sdr recipe

---

uhd.lwr

I've updated to the latest 4.6 release, because 4.2 fails to build on Ubuntu 24.04.

uhd: Update to version 4.6

---

hackrf.lwr

The hackrf package fails to build if FFTW is not installed.

hackrf: Add fftw dependency

---

gr-foo.lwr
gr-ieee-80211.lwr

GNU Radio 3.10 was released nearly three years ago, so I think it makes sense to update the PyBOMBS recipes that still point at earlier versions.

Update gr-foo and gr-ieee-80211 to GNU Radio 3.10
